name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.1.1=h6406543_9
  - h5py=3.7.0=nompi_py37hc97082c_100
  - pandas=1.3.4=py37he8f5f7f_1
  - pytorch=1.10.0=py3.7_cuda11.1_cudnn8.0.5_0
  - torchvision=0.11.1=py37_cu111
  - imgaug=0.4.0=pyhd8ed1ab_1
  - matplotlib-base=3.5.0=py37h1058ff1_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - scipy=1.7.3=py37hf2a6cf1_0
  - munch=2.5.0=py_0
  - opencv=4.5.3=py37h89c1867_5
  - libopencv=4.5.3=py37hbfc4018_5
  - py-opencv=4.5.3=py37h6531663_5
  - ipykernel=6.5.0=py37h6531663_1